on:
  push:
    paths:
      - laragon.psd1

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: 发布
        env:
          NuGetApiKey: ${{ secrets.NuGetApiKey }}
        shell: pwsh
        run: Publish-Module -Path . -NuGetApiKey $env:NuGetApiKey
