on:
  push:
    paths:
      - laragon.psd1

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 下载源码
        run: git clone --depth=1 ${{ github.repositoryUrl }} laragon

      - name: 发布
        shell: pwsh
        run: Publish-Module -Path $PWD\laragon -NuGetApiKey ${{ secrets.NuGetApiKey }}
